title: European Data and Computational Journalism Conference
short_title: DataJConf
email: datajconf@gmail.com
description: > #
        The First European Conference on Data and Computational Journalism aims
        to bring together industry, practitioners and academics in the fields of
        journalism and news production and information, data, social and
        computer sciences, facilitating a multidisciplinary discussion on these
        topics in order to advance research and practice in the broad area of
        Data and Computational Journalism. The conference will be held in Dublin,
        Ireland, on 6th and 7th July, 2017.

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: kramdown

# Site settings
baseurl: ""

# Varibles
sitename: "DataJConf.com"

url: "http://datajconf.com" # the base hostname & protocol for your site
twitter_username: datajconf
github_username:  martinjc

github_repository_url: "martinjc/datajconf.git"
github_repository_name: datajconf
